export type LaGisLayerCategory =
  | 'administrative'
  | 'cadastral'
  | 'land_tenure'
  | 'infrastructure'
  | 'sensitive_sites'
  | 'environment'
  | 'terrain';

export type LaGisAnalysisMode = 'corridor_intersect' | 'parcel_source' | 'informational';

export interface LaGisLayerDef {
  code: string;
  label: string;
  category: LaGisLayerCategory;
  geometryTypes: Array<'Point' | 'LineString' | 'Polygon'>;
  featureClassCodes: string[];
  clearanceType?: string;
  requiredForOverlay: boolean;
  analysisMode: LaGisAnalysisMode;
}

/** Standard GIS layers for automatic LA overlay analysis (Feature Class Catalog codes). */
export const LA_GIS_OVERLAY_LAYERS: readonly LaGisLayerDef[] = [
  // Administrative boundaries
  {
    code: 'village_boundary',
    label: 'Village Boundary',
    category: 'administrative',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['village_boundary', 'village', 'gram_panchayat_boundary'],
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'revenue_village',
    label: 'Revenue Village',
    category: 'administrative',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['revenue_village', 'rev_village'],
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'district_boundary',
    label: 'District Boundary',
    category: 'administrative',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['district_boundary', 'district', 'districts'],
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'tehsil',
    label: 'Tehsil',
    category: 'administrative',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['tehsil', 'tehsil_boundary', 'sub_district'],
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'block',
    label: 'Block',
    category: 'administrative',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['block', 'block_boundary', 'development_block'],
    requiredForOverlay: false,
    analysisMode: 'corridor_intersect',
  },

  // Cadastral
  {
    code: 'khasra_boundary',
    label: 'Khasra Boundary',
    category: 'cadastral',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['khasra_boundary', 'khasra', 'survey_parcel', 'la_parcels', 'cadastral_parcels'],
    requiredForOverlay: true,
    analysisMode: 'parcel_source',
  },
  {
    code: 'khata_boundary',
    label: 'Khata Boundary',
    category: 'cadastral',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['khata_boundary', 'khata'],
    requiredForOverlay: true,
    analysisMode: 'parcel_source',
  },
  {
    code: 'land_ownership',
    label: 'Land Ownership',
    category: 'cadastral',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['land_ownership', 'ownership', 'land_parcels', 'revenue_parcels'],
    requiredForOverlay: true,
    analysisMode: 'parcel_source',
  },

  // Land tenure — corridor overlay triggers clearances
  {
    code: 'government_land',
    label: 'Government Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['government_land', 'govt_land', 'government'],
    clearanceType: 'revenue',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'forest_land',
    label: 'Forest Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['forest_land', 'forest', 'forest_area'],
    clearanceType: 'forest_fca',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'civil_soyam_land',
    label: 'Civil Soyam Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['civil_soyam_land', 'civil_soyam', 'soyam'],
    clearanceType: 'forest_fca',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'van_panchayat',
    label: 'Van Panchayat',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['van_panchayat', 'van_panchayat_land'],
    clearanceType: 'gram_panchayat_resolution',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'reserved_forest',
    label: 'Reserved Forest',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['reserved_forest', 'rf_boundary'],
    clearanceType: 'forest_fca',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'protected_forest',
    label: 'Protected Forest',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['protected_forest', 'pf_boundary'],
    clearanceType: 'forest_fca',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'revenue_land',
    label: 'Revenue Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['revenue_land', 'revenue'],
    clearanceType: 'revenue',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'gram_sabha_land',
    label: 'Gram Sabha Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['gram_sabha_land', 'gram_sabha', 'panchayat_land'],
    clearanceType: 'gram_panchayat_resolution',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'nazul_land',
    label: 'Nazul Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['nazul_land', 'nazul'],
    clearanceType: 'revenue',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },

  // Infrastructure crossings
  {
    code: 'pwd_road',
    label: 'PWD Road',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['pwd_road', 'pwd_roads', 'district_road'],
    clearanceType: 'pwd_noc',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'national_highway',
    label: 'National Highway',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['national_highway', 'nh', 'nh_network'],
    clearanceType: 'nhai_permission',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'state_highway',
    label: 'State Highway',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['state_highway', 'sh', 'state_road'],
    clearanceType: 'state_highway',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'pmgsy_roads',
    label: 'PMGSY Roads',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['pmgsy_roads', 'pmgsy', 'rural_road'],
    clearanceType: 'state_highway',
    requiredForOverlay: false,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'railways',
    label: 'Railways',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['railways', 'railway', 'rail_line'],
    clearanceType: 'railway_crossing',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'river',
    label: 'River',
    category: 'infrastructure',
    geometryTypes: ['LineString', 'Polygon'],
    featureClassCodes: ['river', 'rivers', 'stream', 'nadi'],
    clearanceType: 'river_crossing',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'canal',
    label: 'Canal',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['canal', 'canals', 'irrigation_canal'],
    clearanceType: 'canal_crossing',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'lake',
    label: 'Lake',
    category: 'infrastructure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['lake', 'lakes', 'tal', 'pond'],
    clearanceType: 'environmental_clearance',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'existing_water_pipeline',
    label: 'Existing Water Pipeline',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['existing_water_pipeline', 'water_pipeline', 'existing_pipeline'],
    clearanceType: 'utility_crossing',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'existing_sewer_line',
    label: 'Existing Sewer Line',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['existing_sewer_line', 'sewer_line', 'existing_sewer'],
    clearanceType: 'utility_crossing',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'electric_line',
    label: 'Electric Line',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['electric_line', 'power_line', 'ht_line', 'lt_line'],
    clearanceType: 'electric_crossing',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'gas_pipeline',
    label: 'Gas Pipeline',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['gas_pipeline', 'png_pipeline'],
    clearanceType: 'gas_pipeline_noc',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'telecom_ofc',
    label: 'Telecom OFC',
    category: 'infrastructure',
    geometryTypes: ['LineString'],
    featureClassCodes: ['telecom_ofc', 'ofc', 'fiber_cable'],
    clearanceType: 'telecom_ofc_perm',
    requiredForOverlay: false,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'airport_zone',
    label: 'Airport Zone / Obstacle Limitation',
    category: 'infrastructure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['airport_zone', 'airport', 'aai_obstacle', 'flight_path'],
    clearanceType: 'airport_noc',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'municipality_land',
    label: 'Municipality / ULB Land',
    category: 'land_tenure',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['municipality_land', 'municipal', 'ulb_land'],
    clearanceType: 'municipality_permission',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },

  // Sensitive sites
  {
    code: 'buildings',
    label: 'Buildings',
    category: 'sensitive_sites',
    geometryTypes: ['Polygon', 'Point'],
    featureClassCodes: ['buildings', 'building', 'structure'],
    clearanceType: 'structure_impact',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'schools',
    label: 'Schools',
    category: 'sensitive_sites',
    geometryTypes: ['Point', 'Polygon'],
    featureClassCodes: ['schools', 'school'],
    clearanceType: 'sensitive_site',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'hospitals',
    label: 'Hospitals',
    category: 'sensitive_sites',
    geometryTypes: ['Point', 'Polygon'],
    featureClassCodes: ['hospitals', 'hospital', 'health_center'],
    clearanceType: 'sensitive_site',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'temples',
    label: 'Temples',
    category: 'sensitive_sites',
    geometryTypes: ['Point', 'Polygon'],
    featureClassCodes: ['temples', 'temple', 'religious_site'],
    clearanceType: 'religious_site',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'archaeological_sites',
    label: 'Archaeological Sites',
    category: 'sensitive_sites',
    geometryTypes: ['Point', 'Polygon'],
    featureClassCodes: ['archaeological_sites', 'asi_monument', 'heritage_site'],
    clearanceType: 'archaeological_clearance',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },

  // Environment
  {
    code: 'eco_sensitive_zones',
    label: 'Eco Sensitive Zones',
    category: 'environment',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['eco_sensitive_zones', 'esz', 'eco_sensitive'],
    clearanceType: 'pollution_clearance',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'wildlife_sanctuary',
    label: 'Wildlife Sanctuary',
    category: 'environment',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['wildlife_sanctuary', 'sanctuary', 'ws_boundary'],
    clearanceType: 'wildlife_clearance',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'national_park',
    label: 'National Park',
    category: 'environment',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['national_park', 'np_boundary'],
    clearanceType: 'forest_fca',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
  {
    code: 'wetlands',
    label: 'Wetlands',
    category: 'environment',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['wetlands', 'wetland', 'ramsar'],
    clearanceType: 'environmental_clearance',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },

  // Terrain
  {
    code: 'contour',
    label: 'Contour',
    category: 'terrain',
    geometryTypes: ['LineString'],
    featureClassCodes: ['contour', 'contours'],
    requiredForOverlay: false,
    analysisMode: 'informational',
  },
  {
    code: 'dem',
    label: 'DEM',
    category: 'terrain',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['dem', 'digital_elevation'],
    requiredForOverlay: false,
    analysisMode: 'informational',
  },
  {
    code: 'slope',
    label: 'Slope',
    category: 'terrain',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['slope', 'slope_map'],
    requiredForOverlay: false,
    analysisMode: 'informational',
  },
  {
    code: 'landslide_zone',
    label: 'Landslide Zone',
    category: 'terrain',
    geometryTypes: ['Polygon'],
    featureClassCodes: ['landslide_zone', 'landslide', 'hazard_zone'],
    clearanceType: 'landslide_risk',
    requiredForOverlay: true,
    analysisMode: 'corridor_intersect',
  },
] as const;

export const LA_GIS_LAYER_CATEGORIES: Array<{ code: LaGisLayerCategory; label: string }> = [
  { code: 'administrative', label: 'Administrative Boundaries' },
  { code: 'cadastral', label: 'Cadastral & Ownership' },
  { code: 'land_tenure', label: 'Land Tenure' },
  { code: 'infrastructure', label: 'Infrastructure Crossings' },
  { code: 'sensitive_sites', label: 'Sensitive Sites' },
  { code: 'environment', label: 'Environment & Forest' },
  { code: 'terrain', label: 'Terrain & Hazard' },
];

export function findGisLayerByFeatureClassCode(code: string): LaGisLayerDef | undefined {
  const normalized = code.trim().toLowerCase();
  return LA_GIS_OVERLAY_LAYERS.find((layer) =>
    layer.featureClassCodes.some((alias) => alias.toLowerCase() === normalized),
  );
}
