export const OM_ASSET_CATALOG = [
  { group: 'Source Infrastructure', subcategory: 'Spring Sources', typeCode: 'spring_source' },
  { group: 'Source Infrastructure', subcategory: 'Gadhera Source', typeCode: 'gadhera_source' },
  { group: 'Source Infrastructure', subcategory: 'River Intakes', typeCode: 'river_intake' },
  { group: 'Source Infrastructure', subcategory: 'Bore Wells', typeCode: 'bore_well' },
  { group: 'Source Infrastructure', subcategory: 'Collection Chambers', typeCode: 'collection_chamber' },
  { group: 'Transmission Infrastructure', subcategory: 'Gravity Mains', typeCode: 'gravity_main' },
  { group: 'Transmission Infrastructure', subcategory: 'Rising Mains', typeCode: 'rising_main' },
  { group: 'Transmission Infrastructure', subcategory: 'Valve Chambers', typeCode: 'valve_chamber' },
  { group: 'Transmission Infrastructure', subcategory: 'Air Valves', typeCode: 'air_valve' },
  { group: 'Transmission Infrastructure', subcategory: 'Scour Valves', typeCode: 'scour_valve' },
  { group: 'Storage Infrastructure', subcategory: 'GLSR', typeCode: 'glsr' },
  { group: 'Storage Infrastructure', subcategory: 'OHT', typeCode: 'oht' },
  { group: 'Storage Infrastructure', subcategory: 'CWR', typeCode: 'cwr' },
  { group: 'Mechanical Infrastructure', subcategory: 'Pumps', typeCode: 'pump' },
  { group: 'Mechanical Infrastructure', subcategory: 'Motors', typeCode: 'motor' },
  { group: 'Mechanical Infrastructure', subcategory: 'Flow Meters', typeCode: 'flow_meter' },
  { group: 'Mechanical Infrastructure', subcategory: 'Chlorination Systems', typeCode: 'chlorination_system' },
  { group: 'Electrical Infrastructure', subcategory: 'Transformers', typeCode: 'transformer' },
  { group: 'Electrical Infrastructure', subcategory: 'HT Lines', typeCode: 'ht_line' },
  { group: 'Electrical Infrastructure', subcategory: 'LT Panels', typeCode: 'lt_panel' },
  { group: 'Electrical Infrastructure', subcategory: 'DG Sets', typeCode: 'dg_set' },
  { group: 'Electrical Infrastructure', subcategory: 'Solar Systems', typeCode: 'solar_system' },
  { group: 'Distribution Infrastructure', subcategory: 'Distribution Mains', typeCode: 'distribution_main' },
  { group: 'Distribution Infrastructure', subcategory: 'Sub-Mains', typeCode: 'sub_main' },
  { group: 'Distribution Infrastructure', subcategory: 'Service Connections', typeCode: 'service_connection' },
  { group: 'Consumer Infrastructure', subcategory: 'FHTC Connections', typeCode: 'fhtc_connection' },
  { group: 'Consumer Infrastructure', subcategory: 'Consumer Meters', typeCode: 'consumer_meter' },
] as const;

/** Short codes used in O&M asset IDs: OM-{scheme}-{abbrev}-{seq} */
export const OM_ASSET_TYPE_ABBREV: Record<string, string> = {
  spring_source: 'SPR',
  gadhera_source: 'GDS',
  river_intake: 'INT',
  bore_well: 'BRW',
  collection_chamber: 'CCH',
  gravity_main: 'GRV',
  rising_main: 'RSM',
  valve_chamber: 'VCH',
  air_valve: 'AVV',
  scour_valve: 'SCV',
  glsr: 'GLSR',
  oht: 'OHT',
  cwr: 'CWR',
  pump: 'PMP',
  motor: 'MTR',
  flow_meter: 'FLM',
  chlorination_system: 'CHL',
  transformer: 'TRF',
  ht_line: 'HTL',
  lt_panel: 'LTP',
  dg_set: 'DGS',
  solar_system: 'SLR',
  distribution_main: 'DMN',
  sub_main: 'SBM',
  service_connection: 'SVC',
  fhtc_connection: 'FHT',
  consumer_meter: 'CMS',
};

export const CONSTRUCTION_TO_OM_TYPE: Record<string, string> = {
  source: 'spring_source',
  gadhera: 'gadhera_source',
  gadhera_source: 'gadhera_source',
  intake: 'river_intake',
  borewell: 'bore_well',
  bore_well: 'bore_well',
  gravity_main: 'gravity_main',
  rising_main: 'rising_main',
  valve_chamber: 'valve_chamber',
  air_valve: 'air_valve',
  scour_valve: 'scour_valve',
  glsr: 'glsr',
  oht: 'oht',
  cwr: 'cwr',
  pump_house: 'pump',
  pump: 'pump',
  motor: 'motor',
  flow_meter: 'flow_meter',
  chlorination: 'chlorination_system',
  transformer: 'transformer',
  distribution_main: 'distribution_main',
  fhtc: 'fhtc_connection',
  consumer: 'fhtc_connection',
};
